import type { Reel } from "./types"

const W3 = "https://media.w3.org/2010/05"
const TV = "https://test-videos.co.uk/vids"

export const MOCK_REELS: Reel[] = [
  {
    id: "r1",
    videoUrl: `${TV}/jellyfish/mp4/h264/720/Jellyfish_720_10s_2MB.mp4`,
    caption: "Why most attention research is measuring the wrong thing",
    sourceType: "paper",
    sourceTitle: "Attention Is All You Need (Vaswani et al., 2017)",
    sourceUrl: "https://arxiv.org/abs/1706.03762",
    durationSec: 28,
  },
  {
    id: "r2",
    videoUrl: `${TV}/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_2MB.mp4`,
    caption: "The bookmark you saved in 2019 is now a 26-second briefing",
    sourceType: "bookmark",
    sourceTitle: "How Discord Stores Trillions of Messages",
    sourceUrl: "https://discord.com/blog/how-discord-stores-trillions-of-messages",
    durationSec: 26,
  },
  {
    id: "r3",
    videoUrl: `${W3}/sintel/trailer.mp4`,
    caption: "Three minutes of a forty-minute talk that actually mattered",
    sourceType: "video",
    sourceTitle: "Bret Victor — Inventing on Principle",
    sourceUrl: "https://www.youtube.com/watch?v=PUv66718DII",
    durationSec: 24,
  },
  {
    id: "r4",
    videoUrl: `${TV}/sintel/mp4/h264/360/Sintel_360_10s_1MB.mp4`,
    caption: "What changed about transformer scaling laws this quarter",
    sourceType: "paper",
    sourceTitle: "Scaling Laws for Neural Language Models (Kaplan et al.)",
    sourceUrl: "https://arxiv.org/abs/2001.08361",
    durationSec: 30,
  },
  {
    id: "r5",
    videoUrl: `${W3}/video/movie_300.mp4`,
    caption: "A PDF you starred in November, distilled to one claim",
    sourceType: "pdf",
    sourceTitle: "Designing Data-Intensive Applications — Ch. 7",
    sourceUrl: "https://dataintensive.net/",
    durationSec: 27,
  },
  {
    id: "r6",
    videoUrl: `${TV}/jellyfish/mp4/h264/360/Jellyfish_360_10s_1MB.mp4`,
    caption: "The interface idea you keep rediscovering, named",
    sourceType: "bookmark",
    sourceTitle: "Notes on Sketching the Future — A. Kay",
    sourceUrl: "https://worrydream.com/refs/Kay-EarlyHistory.pdf",
    durationSec: 25,
  },
  {
    id: "r7",
    videoUrl: `${W3}/bunny/movie.mp4`,
    caption: "Two minutes of an hour-long lecture, only the part with the answer",
    sourceType: "video",
    sourceTitle: "Andrej Karpathy — Intro to LLMs",
    sourceUrl: "https://www.youtube.com/watch?v=zjkBMFhNj_g",
    durationSec: 29,
  },
  {
    id: "r8",
    videoUrl: `${TV}/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_1MB.mp4`,
    caption: "Why your saved papers about diffusion all said the same thing",
    sourceType: "paper",
    sourceTitle: "Denoising Diffusion Probabilistic Models",
    sourceUrl: "https://arxiv.org/abs/2006.11239",
    durationSec: 28,
  },
  {
    id: "r9",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    caption: "The blog post you swore you'd revisit, finally revisited",
    sourceType: "bookmark",
    sourceTitle: "The Grug Brained Developer",
    sourceUrl: "https://grugbrain.dev/",
    durationSec: 24,
  },
  {
    id: "r10",
    videoUrl: `${W3}/sintel/trailer.mp4`,
    caption: "Last reel of the drop. Tomorrow, a new ten.",
    sourceType: "video",
    sourceTitle: "Daily drop closing reel",
    sourceUrl: "https://better-scroll.app/about",
    durationSec: 22,
  },
]
